version: 2
archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make generate_schema
builds:
- binary: pulumi-resource-lbrlabs-eks
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/lbrlabs/pulumi-lbrlabs-eks/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-lbrlabs-eks/
changelog:
  disable: true
release:
  disable: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
