// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Eks.Inputs
{

    /// <summary>
    /// Configuration for the ingress controller.
    /// </summary>
    public sealed class IngressConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalConfig")]
        private InputMap<string>? _additionalConfig;

        /// <summary>
        /// Additional configuration for the ingress controller.
        /// </summary>
        public InputMap<string> AdditionalConfig
        {
            get => _additionalConfig ?? (_additionalConfig = new InputMap<string>());
            set => _additionalConfig = value;
        }

        /// <summary>
        /// Whether to allow snippet annotations in the ingress controller.
        /// </summary>
        [Input("allowSnippetAnnotations")]
        public Input<bool>? AllowSnippetAnnotations { get; set; }

        /// <summary>
        /// The number of replicas of the ingress controller.
        /// </summary>
        [Input("controllerReplicas")]
        public Input<int>? ControllerReplicas { get; set; }

        /// <summary>
        /// Enable metrics for the ingress controller.
        /// </summary>
        [Input("enableMetrics")]
        public Input<bool>? EnableMetrics { get; set; }

        /// <summary>
        /// Enable the service monitor for kube-prometheus-stackl.
        /// </summary>
        [Input("enableServiceMonitor")]
        public Input<bool>? EnableServiceMonitor { get; set; }

        /// <summary>
        /// NLB target type for NLB loadbalancers.
        /// </summary>
        [Input("nlbTargetType")]
        public Input<string>? NlbTargetType { get; set; }

        /// <summary>
        /// The namespace to deploy the service monitor to.
        /// </summary>
        [Input("serviceMonitorNamespace")]
        public Input<string>? ServiceMonitorNamespace { get; set; }

        public IngressConfigArgs()
        {
            AllowSnippetAnnotations = false;
            ControllerReplicas = 1;
            EnableMetrics = false;
            EnableServiceMonitor = false;
            NlbTargetType = "ip";
        }
        public static new IngressConfigArgs Empty => new IngressConfigArgs();
    }
}
