// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Eks.Inputs
{

    /// <summary>
    /// The autoscaled node group subnet selector terms.
    /// </summary>
    public sealed class SubnetSelectorTermArgs : global::Pulumi.ResourceArgs
    {
        [Input("subnetIds")]
        private InputList<string>? _subnetIds;
        public InputList<string> SubnetIds
        {
            get => _subnetIds ?? (_subnetIds = new InputList<string>());
            set => _subnetIds = value;
        }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Tags to use to select subnets for nodes to be placed in.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public SubnetSelectorTermArgs()
        {
        }
        public static new SubnetSelectorTermArgs Empty => new SubnetSelectorTermArgs();
    }
}
