// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Eks
{
    [EksResourceType("lbrlabs-eks:index:AttachedFargateProfile")]
    public partial class AttachedFargateProfile : global::Pulumi.ComponentResource
    {
        [Output("profile")]
        public Output<Pulumi.Aws.Eks.FargateProfile> Profile { get; private set; } = null!;

        [Output("role")]
        public Output<Pulumi.Aws.Iam.Role> Role { get; private set; } = null!;


        /// <summary>
        /// Create a AttachedFargateProfile resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AttachedFargateProfile(string name, AttachedFargateProfileArgs args, ComponentResourceOptions? options = null)
            : base("lbrlabs-eks:index:AttachedFargateProfile", name, args ?? new AttachedFargateProfileArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class AttachedFargateProfileArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the cluster to assign the fargate profile to.
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        [Input("selectors", required: true)]
        private InputList<Pulumi.Aws.Eks.Inputs.FargateProfileSelectorArgs>? _selectors;
        public InputList<Pulumi.Aws.Eks.Inputs.FargateProfileSelectorArgs> Selectors
        {
            get => _selectors ?? (_selectors = new InputList<Pulumi.Aws.Eks.Inputs.FargateProfileSelectorArgs>());
            set => _selectors = value;
        }

        [Input("subnetIds", required: true)]
        private InputList<string>? _subnetIds;

        /// <summary>
        /// The subnet IDs to use for the fargate profile.
        /// </summary>
        public InputList<string> SubnetIds
        {
            get => _subnetIds ?? (_subnetIds = new InputList<string>());
            set => _subnetIds = value;
        }

        public AttachedFargateProfileArgs()
        {
        }
        public static new AttachedFargateProfileArgs Empty => new AttachedFargateProfileArgs();
    }
}
