# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Callable, Mapping, Optional, Sequence, Union, overload
from . import _utilities
import pulumi_aws

__all__ = ['AttachedFargateProfileArgs', 'AttachedFargateProfile']

@pulumi.input_type
class AttachedFargateProfileArgs:
    def __init__(__self__, *,
                 cluster_name: pulumi.Input[str],
                 selectors: pulumi.Input['pulumi_aws.eks.FargateProfileSelectorArgs'],
                 subnet_ids: pulumi.Input[Sequence[pulumi.Input[str]]]):
        """
        The set of arguments for constructing a AttachedFargateProfile resource.
        :param pulumi.Input[str] cluster_name: The name of the cluster to assign the fargate profile to.
        :param pulumi.Input['pulumi_aws.eks.FargateProfileSelectorArgs'] selectors: The selectors for the fargate profile.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] subnet_ids: The subnet IDs to use for the fargate profile.
        """
        AttachedFargateProfileArgs._configure(
            lambda key, value: pulumi.set(__self__, key, value),
            cluster_name=cluster_name,
            selectors=selectors,
            subnet_ids=subnet_ids,
        )
    @staticmethod
    def _configure(
             _setter: Callable[[Any, Any], None],
             cluster_name: pulumi.Input[str],
             selectors: pulumi.Input['pulumi_aws.eks.FargateProfileSelectorArgs'],
             subnet_ids: pulumi.Input[Sequence[pulumi.Input[str]]],
             opts: Optional[pulumi.ResourceOptions]=None):
        _setter("cluster_name", cluster_name)
        _setter("selectors", selectors)
        _setter("subnet_ids", subnet_ids)

    @property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Input[str]:
        """
        The name of the cluster to assign the fargate profile to.
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "cluster_name", value)

    @property
    @pulumi.getter
    def selectors(self) -> pulumi.Input['pulumi_aws.eks.FargateProfileSelectorArgs']:
        """
        The selectors for the fargate profile.
        """
        return pulumi.get(self, "selectors")

    @selectors.setter
    def selectors(self, value: pulumi.Input['pulumi_aws.eks.FargateProfileSelectorArgs']):
        pulumi.set(self, "selectors", value)

    @property
    @pulumi.getter(name="subnetIds")
    def subnet_ids(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        """
        The subnet IDs to use for the fargate profile.
        """
        return pulumi.get(self, "subnet_ids")

    @subnet_ids.setter
    def subnet_ids(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "subnet_ids", value)


class AttachedFargateProfile(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_name: Optional[pulumi.Input[str]] = None,
                 selectors: Optional[pulumi.Input[pulumi.InputType['pulumi_aws.eks.FargateProfileSelectorArgs']]] = None,
                 subnet_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 __props__=None):
        """
        Create a AttachedFargateProfile resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] cluster_name: The name of the cluster to assign the fargate profile to.
        :param pulumi.Input[pulumi.InputType['pulumi_aws.eks.FargateProfileSelectorArgs']] selectors: The selectors for the fargate profile.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] subnet_ids: The subnet IDs to use for the fargate profile.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AttachedFargateProfileArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AttachedFargateProfile resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param AttachedFargateProfileArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AttachedFargateProfileArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            kwargs = kwargs or {}
            def _setter(key, value):
                kwargs[key] = value
            AttachedFargateProfileArgs._configure(_setter, **kwargs)
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cluster_name: Optional[pulumi.Input[str]] = None,
                 selectors: Optional[pulumi.Input[pulumi.InputType['pulumi_aws.eks.FargateProfileSelectorArgs']]] = None,
                 subnet_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AttachedFargateProfileArgs.__new__(AttachedFargateProfileArgs)

            if cluster_name is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_name'")
            __props__.__dict__["cluster_name"] = cluster_name
            if not isinstance(selectors, pulumi_aws.eks.FargateProfileSelectorArgs):
                selectors = selectors or {}
                def _setter(key, value):
                    selectors[key] = value
                pulumi_aws.eks.FargateProfileSelectorArgs._configure(_setter, **selectors)
            if selectors is None and not opts.urn:
                raise TypeError("Missing required property 'selectors'")
            __props__.__dict__["selectors"] = selectors
            if subnet_ids is None and not opts.urn:
                raise TypeError("Missing required property 'subnet_ids'")
            __props__.__dict__["subnet_ids"] = subnet_ids
            __props__.__dict__["profile"] = None
            __props__.__dict__["role"] = None
        super(AttachedFargateProfile, __self__).__init__(
            'lbrlabs-eks:index:AttachedFargateProfile',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter
    def profile(self) -> pulumi.Output['pulumi_aws.eks.FargateProfile']:
        return pulumi.get(self, "profile")

    @property
    @pulumi.getter
    def role(self) -> pulumi.Output['pulumi_aws.iam.Role']:
        return pulumi.get(self, "role")

