// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.LbrlabsEks
{
    [LbrlabsEksResourceType("lbrlabs-eks:index:Cluster")]
    public partial class Cluster : global::Pulumi.ComponentResource
    {
        [Output("controlPlane")]
        public Output<Pulumi.Aws.Eks.Cluster> ControlPlane { get; private set; } = null!;

        /// <summary>
        /// The kubeconfig for this cluster.
        /// </summary>
        [Output("kubeconfig")]
        public Output<string> Kubeconfig { get; private set; } = null!;

        [Output("oidcProvider")]
        public Output<Pulumi.Aws.Iam.OpenIdConnectProvider> OidcProvider { get; private set; } = null!;

        [Output("systemNodes")]
        public Output<Pulumi.Aws.Eks.NodeGroup> SystemNodes { get; private set; } = null!;


        /// <summary>
        /// Create a Cluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Cluster(string name, ClusterArgs args, ComponentResourceOptions? options = null)
            : base("lbrlabs-eks:index:Cluster", name, args ?? new ClusterArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ClusterArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterSubnetIds", required: true)]
        private InputList<string>? _clusterSubnetIds;
        public InputList<string> ClusterSubnetIds
        {
            get => _clusterSubnetIds ?? (_clusterSubnetIds = new InputList<string>());
            set => _clusterSubnetIds = value;
        }

        [Input("systemNodeSubnetIds", required: true)]
        private InputList<string>? _systemNodeSubnetIds;
        public InputList<string> SystemNodeSubnetIds
        {
            get => _systemNodeSubnetIds ?? (_systemNodeSubnetIds = new InputList<string>());
            set => _systemNodeSubnetIds = value;
        }

        /// <summary>
        /// The VPC ID to create the cluster in.
        /// </summary>
        [Input("vpcId", required: true)]
        public Input<string> VpcId { get; set; } = null!;

        public ClusterArgs()
        {
        }
        public static new ClusterArgs Empty => new ClusterArgs();
    }
}
